# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metaweardata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='metaweardata.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12metaweardata.proto\"0\n\rMWValueTriple\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\t\n\x01z\x18\x03 \x02(\x01\"\x88\x02\n\x0cMetaWearData\x12 \n\x04type\x18\x01 \x02(\x0e\x32\x12.MetaWearData.Type\x12\x11\n\ttimestamp\x18\x02 \x02(\x03\x12\t\n\x01w\x18\x03 \x01(\x02\x12\t\n\x01x\x18\x04 \x01(\x02\x12\t\n\x01y\x18\x05 \x01(\x02\x12\t\n\x01z\x18\x06 \x01(\x02\x12\x1b\n\x03\x61\x63\x63\x18\x07 \x01(\x0b\x32\x0e.MWValueTriple\x12\x1c\n\x04gyro\x18\x08 \x01(\x0b\x32\x0e.MWValueTriple\x12\r\n\x05\x65xtra\x18\t \x01(\x03\"M\n\x04Type\x12\x07\n\x03\x41\x43\x43\x10\x00\x12\x08\n\x04GYRO\x10\x01\x12\x0e\n\nQUATERNION\x10\x02\x12\n\n\x06SWITCH\x10\x03\x12\x0b\n\x07\x42\x41TTERY\x10\x04\x12\t\n\x05\x46USED\x10\x05\x42\x15\n\x13\x63om.kinemic.kinemic')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_METAWEARDATA_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='MetaWearData.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACC', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GYRO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUATERNION', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SWITCH', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BATTERY', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FUSED', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=260,
  serialized_end=337,
)
_sym_db.RegisterEnumDescriptor(_METAWEARDATA_TYPE)


_MWVALUETRIPLE = _descriptor.Descriptor(
  name='MWValueTriple',
  full_name='MWValueTriple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='MWValueTriple.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='MWValueTriple.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='MWValueTriple.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=70,
)


_METAWEARDATA = _descriptor.Descriptor(
  name='MetaWearData',
  full_name='MetaWearData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MetaWearData.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='MetaWearData.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='MetaWearData.w', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='MetaWearData.x', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='MetaWearData.y', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='MetaWearData.z', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acc', full_name='MetaWearData.acc', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gyro', full_name='MetaWearData.gyro', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extra', full_name='MetaWearData.extra', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _METAWEARDATA_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=337,
)

_METAWEARDATA.fields_by_name['type'].enum_type = _METAWEARDATA_TYPE
_METAWEARDATA.fields_by_name['acc'].message_type = _MWVALUETRIPLE
_METAWEARDATA.fields_by_name['gyro'].message_type = _MWVALUETRIPLE
_METAWEARDATA_TYPE.containing_type = _METAWEARDATA
DESCRIPTOR.message_types_by_name['MWValueTriple'] = _MWVALUETRIPLE
DESCRIPTOR.message_types_by_name['MetaWearData'] = _METAWEARDATA

MWValueTriple = _reflection.GeneratedProtocolMessageType('MWValueTriple', (_message.Message,), dict(
  DESCRIPTOR = _MWVALUETRIPLE,
  __module__ = 'metaweardata_pb2'
  # @@protoc_insertion_point(class_scope:MWValueTriple)
  ))
_sym_db.RegisterMessage(MWValueTriple)

MetaWearData = _reflection.GeneratedProtocolMessageType('MetaWearData', (_message.Message,), dict(
  DESCRIPTOR = _METAWEARDATA,
  __module__ = 'metaweardata_pb2'
  # @@protoc_insertion_point(class_scope:MetaWearData)
  ))
_sym_db.RegisterMessage(MetaWearData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\023com.kinemic.kinemic'))
# @@protoc_insertion_point(module_scope)
